"""Deterministic synthetic fitting corpus: mixed-register paragraphs, seeded.

The committed data/prompts.txt (regenerated by `lens.py make-data`) is the source of truth
for fits — this generator only exists to reproduce it. Register diversity matters more than
factual accuracy here: the Jacobian is averaged over ordinary in-distribution text, so the
corpus mixes encyclopedic prose, instructions, narrative, Q&A, code commentary, and list
prose, each ~90-140 words so most prompts reach the 128-token fitting cap.
"""
import random

TOPICS = ["glass", "harbors", "fermentation", "typography", "glaciers", "beekeeping",
          "railways", "ceramics", "tides", "orchards", "bridges", "weaving", "volcanoes",
          "clockmaking", "coral reefs", "grain storage", "papermaking", "migration",
          "lighthouses", "soil", "telescopes", "canals", "cheese", "wind power", "maps"]
PLACES = ["the northern coast", "central Anatolia", "the river delta", "the high plateau",
          "the old quarter", "the island chain", "the borderlands", "the valley floor"]
ADJS = ["early", "modern", "traditional", "industrial", "coastal", "seasonal", "regional",
        "experimental", "abandoned", "restored"]
VERBS = ["depends on", "developed alongside", "was transformed by", "still relies on",
         "gradually replaced", "competes with", "predates", "shaped the growth of"]
TOOLS = ["a sharp knife", "a level surface", "clean water", "steady heat", "patience",
         "a measuring tape", "good ventilation", "cold storage", "a fine sieve"]
NAMES = ["Mara", "Old Teodor", "the ferryman", "my grandmother", "the apprentice",
         "Ilya", "the surveyor", "Sister Ana"]


def _sentences(rng, family, topic):
    t, place, adj = topic, rng.choice(PLACES), rng.choice(ADJS)
    if family == "encyclopedic":
        return [
            f"The history of {t} in {place} stretches back several centuries.",
            f"{adj.capitalize()} {t} {rng.choice(VERBS)} the local economy in ways that are still visible today.",
            f"Most accounts agree that the practice spread along trade routes before written records mention it.",
            f"By the middle of the nineteenth century, {t} had become a defining feature of daily life there.",
            f"Scholars continue to debate how much of the surviving technique is original and how much was reinvented later.",
            f"What is certain is that {t} left a durable mark on the landscape and the language of the region.",
            f"Museums in the area now devote entire wings to the subject, and interest keeps growing.",
        ]
    if family == "howto":
        return [
            f"Before you begin working with {t}, gather {rng.choice(TOOLS)} and {rng.choice(TOOLS)}.",
            f"Start by preparing your workspace, because {t} is unforgiving of clutter and haste.",
            f"Work in small, repeatable steps, checking your progress against the previous stage each time.",
            f"If something looks wrong, stop immediately and trace the problem back to its source.",
            f"A common beginner mistake is rushing the early stages, which quietly ruins the final result.",
            f"Once the main work is done, let everything rest before you judge the outcome.",
            f"With practice, the whole process becomes intuitive, and you will develop your own shortcuts.",
        ]
    if family == "narrative":
        who = rng.choice(NAMES)
        return [
            f"{who} had spent a lifetime around {t}, and it showed in every deliberate movement.",
            f"That morning on {place}, the weather turned before anyone expected it to.",
            f"\"You learn to read the signs,\" {who} said, not looking up from the work.",
            f"The younger ones watched carefully, knowing this knowledge was not written down anywhere.",
            f"By afternoon the task was finished, and nobody mentioned how close it had come to failing.",
            f"Later, walking home, I understood why people here still spoke of {t} with a kind of reverence.",
            f"Some skills survive only because someone refuses to let them die.",
        ]
    if family == "qa":
        return [
            f"Question: why does {t} matter so much in {place}?",
            f"Answer: mostly because the local conditions make alternatives expensive or unreliable.",
            f"Question: how long does it take to learn the basics?",
            f"Answer: a diligent beginner can be useful within a season, but real judgment takes years.",
            f"Question: what is the most common misconception about {t}?",
            f"Answer: that it is simple. The surface of the craft hides an enormous amount of accumulated decision-making.",
            f"Question: is the tradition at risk of disappearing?",
            f"Answer: less than it was a decade ago, thanks to a small number of stubborn practitioners.",
        ]
    if family == "code":
        return [
            f"# This module schedules the nightly batch jobs for the {t.replace(' ', '_')} pipeline.",
            f"# Each job reads yesterday's snapshot, applies the {adj} filters, and writes a summary table.",
            f"# NOTE: retries are capped at three because the upstream API throttles aggressively.",
            f"# The queue is drained in priority order; ties are broken by submission time.",
            f"# If the checkpoint file is missing we rebuild it from the raw logs, which is slow but safe.",
            f"# Downstream consumers assume the summary table is complete, so partial writes must never be committed.",
            f"# See the runbook for what to do when the {t} feed goes quiet for more than an hour.",
        ]
    return [  # "list" family: enumerated prose
        f"There are a few things worth knowing about {t} before visiting {place}.",
        f"First, the busy season is short, and everything interesting happens inside it.",
        f"Second, the {adj} varieties are the ones locals actually care about, whatever the guidebooks say.",
        f"Third, the vocabulary is precise: using the wrong word marks you as an outsider instantly.",
        f"Fourth, most of the real activity happens early in the morning, well before the crowds arrive.",
        f"Fifth, the people who know the most are rarely the ones doing the talking.",
        f"Keep those points in mind and the whole subject opens up quickly.",
    ]


FAMILIES = ["encyclopedic", "howto", "narrative", "qa", "code", "list"]


def make_prompts(n=300, seed=0):
    """n deterministic paragraphs (~90-140 words), cycling families over shuffled topics."""
    rng = random.Random(seed)
    out = []
    while len(out) < n:
        family = FAMILIES[len(out) % len(FAMILIES)]
        topic = rng.choice(TOPICS)
        sents = _sentences(rng, family, topic)
        k = rng.randint(6, len(sents))
        out.append(" ".join(sents[:k]))
    return out


def make_agreement_prompts(n=50, seed=1):
    """Held-out prompts for the top-1-agreement eval (disjoint seed from the fit corpus)."""
    return make_prompts(n=n, seed=seed)
